import Sequelize from 'sequelize';
import database from '../../database/database';

const LoginCompanyModel = database.define('pessoas', {
    id_pessoas: { type: Sequelize.INTEGER, autoIncrement: true, allowNull: false, primaryKey: true}, 
    nome_fantasia: Sequelize.STRING,
    razao_social: Sequelize.STRING,
    tipo_pessoa: Sequelize.CHAR,
    cpf_cnpj: Sequelize.STRING,
    rg: Sequelize.STRING,
    email: Sequelize.DATE,
    data_nascimento: Sequelize.DATE,
    sexo: Sequelize.CHAR,
    inscricao_estadual: Sequelize.STRING,
    inscricao_municipal: Sequelize.STRING,
    suframa: Sequelize.STRING,
    telefone: Sequelize.STRING,
    celular: Sequelize.STRING,
    id_plano_contas: Sequelize.INTEGER,
    conta_contabil: Sequelize.STRING,
    id_tipo_fornecedor: Sequelize.INTEGER,
    limite_credito: Sequelize.DECIMAL,
    cliente: Sequelize.BIGINT,
    fornecedor: Sequelize.BIGINT,
    vendedor: Sequelize.BIGINT,
    transportadora: Sequelize.BIGINT,
    separador_produto: Sequelize.BIGINT,
    operador_caixa: Sequelize.BIGINT,
    supervisor_caixa: Sequelize.BIGINT,
    cancela_cupom: Sequelize.BIGINT,
    cancela_venda: Sequelize.BIGINT,
    cancela_item_cupom: Sequelize.BIGINT,
    fornece_desconto_caixa: Sequelize.BIGINT,
    entregador_vendas: Sequelize.BIGINT,
    tecnico: Sequelize.BIGINT,
    compra_conta_corrente: Sequelize.BIGINT,
    compra_crediario: Sequelize.BIGINT,
    usuario_master: Sequelize.BIGINT,
    id_condicao_paga_padrao: Sequelize.INTEGER,
    bloqueio_comercial: Sequelize.BIGINT,
    data_criacao: Sequelize.DATE,
    data_alteracao: Sequelize.DATE,
    id_pessoas_vendedor_padrao: Sequelize.INTEGER,
    origem_cadastro: Sequelize.CHAR,
    senha: Sequelize.STRING,
}, 
    {
        tableName: 'pessoas',
        createdAt: false,
        updatedAt: false,
    }
);

export default LoginCompanyModel;